@s6464_KolokwiumPoprawa_HostAddress = http://localhost:5204

GET {{s6464_KolokwiumPoprawa_HostAddress}}/api/visits/1
Accept: application/json

###

POST {{s6464_KolokwiumPoprawa_HostAddress}}/api/visits
Content-Type: application/json

{
  "clientId": 1,
  "mechanicLicenceNumber": "MECH-20230001",
  "services": [
    {
      "serviceName": "Oil Change",
      "serviceFee": 110.0
    },
    {
      "serviceName": "Brake Repair",
      "serviceFee": 280.0
    }
  ]
}

###
